version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: be-parcel:0.0.1
    ports:
      - "8000:8000"
    volumes:
      - .:/app
  db:
    image: postgres:16.1-alpine3.19
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123123
      - POSTGRES_DB=parcel