"""remove table user

Revision ID: 03211e2803bf
Revises: c10db8f9feb8
Create Date: 2024-08-13 01:06:32.940706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '03211e2803bf'
down_revision: Union[str, None] = 'c10db8f9feb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_user_id', table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade() -> None:
    op.create_table('user',
    sa.Column('user_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    # sa.Column('status', postgresql.ENUM('Active', 'Inactive', 'Blocked', name='status'), server_default=sa.text("'Active'::status"), autoincrement=False, nullable=False),
    sa.Column('Date_created', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('role', sa.INTEGER(), server_default=sa.text('2'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'email', name='user_pkey')
    )
    op.create_index('ix_user_user_id', 'user', ['user_id'], unique=False)
    # ### end Alembic commands ###
