"""update profile

Revision ID: 1a3f2d0db80f
Revises: 2a3708950352
Create Date: 2024-11-14 07:21:59.110535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a3f2d0db80f'
down_revision: Union[str, None] = '2a3708950352'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profile', 'gender',
               existing_type=postgresql.ENUM('Male', 'Female', 'Prefer not to respond', name='gender_profile'),
               nullable=False)
    op.alter_column('profile', 'age',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profile', 'age',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('profile', 'gender',
               existing_type=postgresql.ENUM('Male', 'Female', 'Prefer not to respond', name='gender_profile'),
               nullable=True)
    # ### end Alembic commands ###
