"""init

Revision ID: 356ba3944e7f
Revises: 
Create Date: 2024-03-25 10:28:12.904109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '356ba3944e7f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_locker_locker_id'), 'locker', ['locker_id'], unique=False)
    op.create_foreign_key(None, 'order', 'cell', ['receiving_cell_id'], ['cell_id'])
    op.create_foreign_key(None, 'order', 'cell', ['sending_cell_id'], ['cell_id'])
    op.create_foreign_key(None, 'parcel', 'order', ['parcel_id'], ['order_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'parcel', type_='foreignkey')
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_index(op.f('ix_locker_locker_id'), table_name='locker')
    # ### end Alembic commands ###
