"""create a relatonship between shipper and order

Revision ID: 6143ce629d89
Revises: 9b7a85705dea
Create Date: 2024-11-14 10:07:06.669252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6143ce629d89'
down_revision: Union[str, None] = '9b7a85705dea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('name', sa.String(), nullable=True))
    op.add_column('order', sa.Column('shipper_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order', 'account', ['shipper_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_column('order', 'shipper_id')
    op.drop_column('account', 'name')
    # ### end Alembic commands ###
