"""update relationship

Revision ID: 657cd48b3a0c
Revises: 4774a0c47703
Create Date: 2024-08-17 13:52:19.909694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '657cd48b3a0c'
down_revision: Union[str, None] = '4774a0c47703'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
    """
    INSERT INTO role (role_id, name)
    SELECT 1, 'admin' WHERE NOT EXISTS (SELECT 1 FROM role WHERE role_id = 1);
    
    INSERT INTO role (role_id, name)
    SELECT 2, 'user' WHERE NOT EXISTS (SELECT 1 FROM role WHERE role_id = 2);
    
    INSERT INTO role (role_id, name)
    SELECT 3, 'shipper' WHERE NOT EXISTS (SELECT 1 FROM role WHERE role_id = 3);
    """)
    
    op.create_unique_constraint(None, 'account', ['username'])
    op.create_unique_constraint(None, 'account', ['email'])
    op.create_foreign_key(None, 'account', 'role', ['role'], ['role_id'])
    op.create_foreign_key(None, 'order', 'profile', ['sender_id'], ['user_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        DELETE FROM role WHERE role_id IN (1, 2, 3);
        """
    )
    op.drop_constraint(None, 'account', type_='foreignkey')
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_constraint(None, 'account', type_='unique')
    op.drop_constraint(None, 'account', type_='unique')
    # ### end Alembic commands ###
