"""add parcelType

Revision ID: 7d0aad33a6ab
Revises: 09a9bb11bf91
Create Date: 2024-09-30 16:47:04.904819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d0aad33a6ab'
down_revision: Union[str, None] = '09a9bb11bf91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
    """
    INSERT INTO parcel_type (parcel_type_id, name)
    SELECT 1, 'fragile' WHERE NOT EXISTS (SELECT 1 FROM role WHERE parcel_type_id = 1);
    
    
    INSERT INTO parcel_type (parcel_type_id, name)
    SELECT 2, 'liquid' WHERE NOT EXISTS (SELECT 1 FROM role WHERE parcel_type_id = 2);
  
    
    INSERT INTO parcel_type (parcel_type_id, name)
    SELECT 3, 'electronics' WHERE NOT EXISTS (SELECT 1 FROM role WHERE parcel_type_id = 3);
    
    """)
    
    op.add_column('parcel', sa.Column('parcelType', sa.Integer(), nullable=True))
    op.create_foreign_key('parcel_type_fkey', 'parcel', 'parcel_type', ['parcelType'], ['parcel_type_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Delete the inserted parcel types
    op.execute(
        """
        DELETE FROM parcel_type WHERE parcel_type_id IN (1, 2, 3);
        """
    )
    op.drop_constraint('parcel_type_fkey', 'parcel', type_='foreignkey')
    op.drop_column('parcel', 'parcelType')
    # ### end Alembic commands ###
