"""Add date_created and status to user

Revision ID: cb366fe51699
Revises: c1df81b74fb6
Create Date: 2024-07-18 04:47:12.773855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cb366fe51699'
down_revision: Union[str, None] = '76b0ff9e89ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    status_enum = sa.Enum('Active', 'Inactive', name='status')
    status_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('user', sa.Column('status',status_enum, nullable=False,server_default='Active'))
    op.add_column('user', sa.Column('Date_created', sa.DateTime(), nullable=False, server_default=sa.text('NOW()')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'Date_created')
    op.drop_column('user', 'status')
    # ### end Alembic commands ###
