"""Change nullable = true for some attribute for adding information later

Revision ID: d37e6e9e58d7
Revises: 4f1ef490dafd
Create Date: 2024-07-31 19:55:48.391947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd37e6e9e58d7'
down_revision: Union[str, None] = '4f1ef490dafd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
   
