# .github/workflows/deploy.yml
name: CI/CD Pipeline

on:
  push:
    tags:
      - 'v*'         # Match any tag starting with 'v'
      - '*'          # Match any tag

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: backend

      - name: Run tests
        run: pytest

      - name: Get version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t be-parcel:${{ env.VERSION }} .
          docker tag be-parcel:${{ env.VERSION }} be-parcel:latest
        working-directory: backend

      - name: Push Docker image
        run: |
          docker push be-parcel:${{ env.VERSION }}
          docker push be-parcel:latest
        working-directory: backend
